### ISSUE TITLE
リソース設計をする

### ISSUE THREAD

**Issue by rira100000000** [rira100000000/csv_converter#16]
# エレベーターピッチ
[どんなサービスを作るかを考える \| FBC](https://bootcamp.fjord.jp/products/16527)

# ペーパープロトタイプ
[ペーパープロトタイプを作る \| FBC](https://bootcamp.fjord.jp/products/16631)

# 技術構成
https://github.com/rira100000000/csv_converter/wiki/TechnologyStack

# リソース
| method  | path                | discription                                     | 
| ------- | ------------------- | ----------------------------------------------- | 
| GET     | /                   | トップ画面。ログイン済みなら/ordersに自動遷移。 | 
| GET     | /orders             | 注文一覧、内容品変換、クリックポスト変換画面。同じURLでSPA的に動かす | 
|GET     |/contents           | DBから内容品変換ルールを取得  |
| POST    | /contents           | 内容品変換ルール作成                      | 
| GET     | /print              | 印刷画面                                        | 
| GET     | /users/sign_in      | サインイン画面                                  | 
| POST    | /users/sign_in      | サインイン実行                                  | 
| DELETE  | /users/sign_out     | サインアウト実行                                | 
| GET     | /users/password/new | パスワード再設定画面                            | 
| PATCH   | /users/password     | パスワード変更                                  | 
| GET     | /users/sign_up      | サインアップ画面                                | 
| POST    | /users              | ユーザー登録実行                                | 
| PATCH   | /users              | ユーザー情報更新                                | 
| DELETE  | /users              | ユーザー削除                                    | 

## モーダル
* ユーザー情報編集画面はモーダルで作る

**Comment by maedana** [comment]
### 注文関連について
> GET | /orders | 注文一覧、内容品変換、クリックポスト変換画面。同じURLでSPA的に動かす
-- | -- | --

ローカルファイル読み込み、表示、クリックポスト用に変換、変換結果ダウンロードを File API使ってやるイメージでしょうか? ( https://developer.mozilla.org/ja/docs/Web/API/File )
そのために上記に関するようなURIが存在しない、という理解でいいですか?

なお、一切の記録が残りませんし、もし途中でブラウザが落ちたりすると作業内容失われると思いますけどいいんでしょうか? また、過去の記録を見たりする必要はないものなんですかね? 何をどこまで処理したんだっけ...?とはならないですか? 印刷機能で自分で印刷して記録を残してね、のスタンスですかね

### 内容品変換ルールについて
更新や削除は不要なんでしょうか? 間違って作ったものは表示され続けることになりそうですけども。

**Comment by rira100000000** [comment]
> ローカルファイル読み込み、表示、クリックポスト用に変換、変換結果ダウンロードを File API使ってやるイメージでしょうか?

はい、そのイメージです。

> なお、一切の記録が残りませんし、もし途中でブラウザが落ちたりすると作業内容失われると思いますけどいいんでしょうか?

変換ルールさえ保存されていれば、残りの情報は復元できるので問題ないという認識です。

> 過去の記録を見たりする必要はないものなんですかね? 

過去の記録についてですが、取っておくメリットは2点あると考えました。
1. 過去の注文一覧を見ることができる
2. 一度変換した注文を再度変換した場合、警告を出せる

1点目については、あくまでも発送作業を楽にするための”変換サービス"なのでファーストリリースの要件ではないかなぁと思っています。
注文管理機能を今後追加するのであればやっていきたいところではありますが、ユーザーの顧客情報をこちら側に保存するというのが歓迎されない可能性も感じます。

2点目については、作業状況を一つずつ確認するのは不便なので、変換を行った注文番号だけ記録するようにし、2回以上変換された場合に警告を出すようにしたいと思います。

>更新や削除は不要なんでしょうか? 間違って作ったものは表示され続けることになりそうですけども。

変換画面には今回の注文情報CSVに存在している項目だけを表示する想定です。
その項目を削除されると変換できなくなってしまいますので、削除機能はありません。
間違って登録した場合は再度CSVの読み込みからやり直してもらうイメージです。
新規作成、編集、削除を行える、変換ルール一覧画面を作る案もあったのですが、誤操作やUIの複雑化に対して得られるメリットを感じられないので不要と判断しています。

### 余談
過去の注文一覧が欲しくなるシナリオとしては「発送完了ボタンを押したのに発送していなかった」とか「発送先に誤りがあった」というものがあると思います。
ただそれらは一次情報であるminne,creema、発送情報の最終確定地点であるクリックポストや郵便追跡の各サービスで確認すべき情報なので、中間地点である本サービスで確認するべきではありません。
そうすると発送作業に特化した本サービスで、過去の注文一覧を眺める理由も別に無いんじゃないかなと思っています。

では、何で印刷機能があるのかというと、ユーザーはスマホやパソコンを見ながら発送作業をしたくないという実体験があります。
多くの作家（販売者）は自宅で作業しているので、パソコンのある場所と梱包スペースが同じ場所にあるとも限らず、スペースはそう広くなく。
スマホの小さい画面を見ながら作業するとスピードが落ちるので、私の経験上スピーディーに発送作業をこなしたいのであれば、紙で管理するのが最適解だと思ってます。
現状のminne、Creemaでは注文一覧の印刷がサポートされていないので、こちらはサポートしたいと考えています。

**Comment by maedana** [comment]
諸々ご丁寧にありがとうございます。ご自身が利用者であるということで深く考えられた上でのことだとよくわかりましたので、このまま進めましょう!!
