### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by rira100000000** [rira100000000/csv_converter#4]
# エレベーターピッチ
[どんなサービスを作るかを考える \| FBC](https://bootcamp.fjord.jp/products/16527)

# ペーパープロトタイプ
[ペーパープロトタイプを作る \| FBC](https://bootcamp.fjord.jp/products/16631)

# 技術構成
https://github.com/rira100000000/csv_converter/wiki/TechnologyStack

# DB設計
```mermaid

erDiagram
    users {
        id BIGINT PK
        email VARCHAR UK "NOT NULL"
        encrypted_password VARCHAR "NOT NULL"
        reset_password_token  VARCHAR UK
        reset_password_sent_at DATETIME
        remember_created_at DATETIME
        created_at DATETIME "NOT NULL"
        updated_at DATETIME "NOT NULL"



    }

    conversions {
        id BIGINT PK
        user_id INTEGER FK,UK
        item VARCHAR UK "NOT NULL"
        content VARCHAR "NOT NULL"
    }

    converteds{
        id BIGINT PK
        order_id VARCHAR UK "NOT NULL"
    }

    users ||--o{ conversions : "1人のユーザーは0以上の変換ルールを持つ"

```

**Comment by maedana** [comment]
- devise使うのだとするとUserテーブルは情報少なすぎるかなーと思います。あとRails想定なら通常`users`, `conversions`というテーブル名になるかなと。
- Conversionのuser_id, itemがUKとなってますが、単体ではなく複合ユニークキーということであってます? なお、itemが元の商品名で、同じ商品名なら同じ内容品名を適用でいいのでユニーク制約ということですかね。同じ商品名だけど違う内容品名を別々につけたい、なんてケースはありえないでしょうか。

**Comment by rira100000000** [comment]
> devise使うのだとするとUserテーブルは情報少なすぎるかなーと思います。
全然足りていませんでした🙇‍♂️
不足していたカラムを追加しました。

> Conversionのuser_id, itemがUKとなってますが、単体ではなく複合ユニークキーということであってます?

はい、その認識であっています。

> itemが元の商品名で、同じ商品名なら同じ内容品名を適用でいいのでユニーク制約ということですかね。

はい、itemが元の商品名、contentが変換先である内容品名です。

> 同じ商品名だけど違う内容品名を別々につけたい、なんてケースはありえないでしょうか。

同じ商品名で別の内容品にしたいという要望はありえますが、かなり限定的な需要になるかと思います。
例えば「Creema 衣類」「minne 衣類」のように内容品にサービス名を記載したい場合が考えられます。

一方で、「商品名を内容品に変換する」というルールにすることでユーザーにそれ以上考えさせないで済む、シンプルな操作性で提供できるとも考えています。
同じ商品名で別の内容品に変換するとなると、変換ルール名を付けるなどする必要が出てくると思うのですが、一部の特殊な需要のために手順や確認項目が増える＝全体の利便性が損なわれるというのは避けたいです。

同じ商品名での登録はできませんが、スペースや記号を入れるなど、ほぼ同じ商品名を付けることは可能なのでユーザー側で対処してもらいたいと思います。

ちなみにですが、このプロトタイプに当たるプログラムは7年ほど運用しており私と家族で利用しています。
一般公開からも1.5年ほど経っていますが、そのような要望は今のところ発生していません。

**Comment by maedana** [comment]
諸々合理的な判断だと思いますので、OKです。
